#!/bin/bash

source .env

if [ -z "${RAILS_MASTER_KEY}" ]; then
    echo "RAILS_MASTER_KEY is not found in .env File"
  exit 1
fi

env RAILS_MASTER_KEY=$RAILS_MASTER_KEY ./bin/rails RAILS_ENV=production  assets:precompile assets:clean
